### ISSUE TITLE
Buttons to move the panel to left/right/bottom quickly

### ISSUE THREAD

**Issue by martin-braun** [yasukotelin/toggle-panel#1]
Hi,

nice extension. Toggling the panel via mouse click is nice for people who don't know about Ctrl+J, but I think it would also be nice to move the panel to the right / buttom / left quickly with a tiny dropdown that is next to the button.

Thanks!

**Comment by butuzov** [comment]
Why not just add hotkeys to the next commands?
* `workbench.action.positionPanelRight`
* `workbench.action.positionPanelLeft`
* `workbench.action.positionPanelBottom`

**Comment by butuzov** [comment]
@martin-braun checkout this solution, you might like this

https://github.com/microsoft/vscode/issues/102105#issuecomment-657265780

**Comment by martin-braun** [comment]
> Why not just add hotkeys to the next commands?
> 
> * `workbench.action.positionPanelRight`
> * `workbench.action.positionPanelLeft`
> * `workbench.action.positionPanelBottom`

Hi. Thank you, I figured this out after I created this issue. I think it still would be nice to be included in this extension, but it's not mandatory to me, anymore. I left this ticket open to let the author decide if he wants to implement it or not.

**Comment by yasukotelin** [comment]
@martin-braun @butuzov 
thanks for this good issue👍🏻  
But this feature seems to already exist.
https://code.visualstudio.com/updates/v1_29#_panel-position-button-to-context-menu

If you want to use only mouse control, you can right click on the panel (TERMINAL, OUTPUT, PROBLEMS...).

**Comment by martin-braun** [comment]
> @martin-braun @butuzov
> thanks for this good issue👍🏻
> But this feature seems to already exist.
> https://code.visualstudio.com/updates/v1_29#_panel-position-button-to-context-menu
> 
> If you want to use only mouse control, you can right click on the panel (TERMINAL, OUTPUT, PROBLEMS...)

Life changing, thanks!
